[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.9"

[[redirects]]
  from = "https://otherboard.org/*"
  to = "https://m.otherboard.org/:splat"
  status = 301
  force = true
