baseURL = "https://m.otherboard.org"

# canonifyURLs = true
languageCode = "en-us"
title = "(m)otherboard"
summary = "Bending the arc of technology from individualistic convenience to collective good."

DefaultContentLanguage = "en"
hasCJKLanguage = true

uglyURLs = false

[outputs]
home = ["html"]
page = ["html"]
# Uncomment if, like above, you're allowing multiple output formats
# page = ["html", "markdown", "plaintext", "asciidoc"]
